---
kind: pipeline
type: ssh
name: default

server:
  host:
    from_secret: host105
  user:
    from_secret: user

clone:
  disable: true

steps:
  - name: greeting
    commands:
      - echo hello world
      - echo hostname

trigger:
  branch:
    - test105
