---
kind: pipeline
name: default

steps:
  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host:
        frome_secret: host
      username:
        frome_secret: user
      key:
        frome_secret: ssh_key
      command_timeout: 10s
      script:
        - echo hello world
        - echo $(hostname)

trigger:
  branch:
    - test105
